# Generated by Django 2.2.6 on 2020-03-16 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=10, null=True)),
                ('add1', models.CharField(max_length=30, null=True)),
                ('add2', models.CharField(max_length=30, null=True)),
                ('f_name', models.CharField(max_length=30, null=True)),
                ('m_name', models.CharField(max_length=30, null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
                ('birth', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Category')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.FileField(null=True, upload_to='')),
                ('mark10', models.FileField(null=True, upload_to='')),
                ('mark12', models.FileField(null=True, upload_to='')),
                ('g_certificate', models.FileField(null=True, upload_to='')),
                ('pg_certificate', models.FileField(null=True, upload_to='')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, null=True)),
                ('board', models.CharField(max_length=100, null=True)),
                ('percent', models.CharField(max_length=10, null=True)),
                ('stream', models.CharField(max_length=30, null=True)),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Qualification')),
            ],
        ),
    ]
