# Generated by Django 2.2.6 on 2020-03-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Date1',
            field=models.DateField(null=True),
        ),
    ]
