# Generated by Django 2.2.6 on 2020-03-16 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0002_notice_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Signup'),
        ),
    ]
