# Generated by Django 2.2.6 on 2020-03-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200316_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification_detail',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Student'),
        ),
    ]
