# Generated by Django 2.2.6 on 2020-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20200318_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rem_date',
            field=models.DateField(null=True),
        ),
    ]
