# Generated by Django 2.2.6 on 2020-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_student_rem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rem',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
